INSERT INTO movies (
    rating,
    movie,
    year,
    country,
    rating_ball,
    overview,
    director,
    screenwriter,
    actors,
    url_logo
) VALUES
      (1, 'The Shawshank Redemption', 1994, 'USA', 9.3,
       'Two imprisoned men bond over years, finding solace and eventual redemption through acts of decency.',
       'Frank Darabont',
       'Stephen King, Frank Darabont',
       'Tim Robbins, Morgan Freeman',
       'https://example.com/img/shawshank.jpg'
      ),
      (2, 'The Godfather', 1972, 'USA', 9.2,
       'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
       'Francis Ford Coppola',
       'Mario Puzo, Francis Ford Coppola',
       'Marlon Brando, Al Pacino, James Caan',
       'https://example.com/img/godfather.jpg'
      ),
      (3, 'The Dark Knight', 2008, 'USA', 9.0,
       'Batman forms an uneasy alliance with a newly minted district attorney as a criminal mastermind unleashes chaos.',
       'Christopher Nolan',
       'Jonathan Nolan, Christopher Nolan',
       'Christian Bale, Heath Ledger, Aaron Eckhart',
       'https://example.com/img/darkknight.jpg'
      ),
      (4, '12 Angry Men', 1957, 'USA', 9.0,
       'A jury holds out in a murder trial, forcing the jurors to question their morals and values.',
       'Sidney Lumet',
       'Reginald Rose',
       'Henry Fonda, Lee J. Cobb, Martin Balsam',
       'https://example.com/img/12angrymen.jpg'
      ),
      (5, 'Schindler''s List', 1993, 'USA', 8.9,
       'In German-occupied Poland, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.',
       'Steven Spielberg',
       'Steven Zaillian, Thomas Keneally',
       'Liam Neeson, Ben Kingsley, Ralph Fiennes',
       'https://example.com/img/schindlerslist.jpg'
      ),
      (6, 'Pulp Fiction', 1994, 'USA', 8.9,
       'The lives of two hitmen, a boxer, and others intertwine in a tale of violence and redemption.',
       'Quentin Tarantino',
       'Quentin Tarantino, Roger Avary',
       'John Travolta, Uma Thurman, Samuel L. Jackson',
       'https://example.com/img/pulpfiction.jpg'
      ),
      (7, 'The Lord of the Rings: The Return of the King', 2003, 'USA', 8.9,
       'Gandalf and Aragorn lead the final battle against Sauron, as Frodo and Sam approach Mount Doom.',
       'Peter Jackson',
       'J.R.R. Tolkien, Fran Walsh, Philippa Boyens, Peter Jackson',
       'Elijah Wood, Ian McKellen, Viggo Mortensen',
       'https://example.com/img/lotr-rotk.jpg'
      ),
      (8, 'Forrest Gump', 1994, 'USA', 8.8,
       'The presidencies of Kennedy and Johnson, the Vietnam War, and more pass before the eyes of an Alabama man.',
       'Robert Zemeckis',
       'Winston Groom, Eric Roth',
       'Tom Hanks, Robin Wright, Gary Sinise',
       'https://example.com/img/forrestgump.jpg'
      ),
      (9, 'Inception', 2010, 'USA', 8.8,
       'A thief who infiltrates dreams must plant an idea in a target''s mind in exchange for his own redemption.',
       'Christopher Nolan',
       'Christopher Nolan',
       'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
       'https://example.com/img/inception.jpg'
      ),
      (10, 'Fight Club', 1999, 'USA', 8.8,
       'An insomniac office worker and a soap maker form an underground fight club that evolves into something more.',
       'David Fincher',
       'Chuck Palahniuk (novel), Jim Uhls (screenplay)',
       'Brad Pitt, Edward Norton, Helena Bonham Carter',
       'https://example.com/img/fightclub.jpg'
      ),
      (
          11,
          'Knockin'' on Heaven''s Door',
          1997,
          'Germany',
          8.629,
          'Two terminally ill men meet in a hospital and decide to escape to the sea. After stealing a car with a bag of cash, they get caught in a chaotic chase involving gangsters, police, and unexpected twists.',
          'Thomas Jahn',
          '{"Thomas Jahn", "Til Schweiger"}',
          '{"Til Schweiger", "Jan Josef Liefers", "Thierry Van Werveke", "Moritz Bleibtreu", "Hub Stapel"}',
          'https://example.com/img/knockin_on_heavens_door.jpg'
      ),
      (
          12,
          'The Godfather',
          1972,
          'USA',
          8.732,
          'The aging patriarch of a mafia family transfers control of his empire to his reluctant son during post-WWII New York.',
          'Francis Ford Coppola',
          '{"Mario Puzo", "Francis Ford Coppola"}',
          '{"Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall", "Richard Castellano"}',
          'https://example.com/img/godfather.jpg'
      ),
      (
          13,
          'Pulp Fiction',
          1994,
          'USA',
          8.619,
          'The lives of two hitmen, a boxer, and a gangster’s wife intertwine in a series of violent, darkly humorous events.',
          'Quentin Tarantino',
          '{"Quentin Tarantino", "Roger Avary"}',
          '{"John Travolta", "Samuel L. Jackson", "Bruce Willis", "Uma Thurman", "Ving Rhames"}',
          'https://example.com/img/pulp_fiction.jpg'
      ),
      (
          14,
          'Operation Y and Shurik''s Other Adventures',
          1965,
          'USSR',
          8.712,
          'Three comedic stories follow Shurik, a nerdy but kind-hearted student, through mishaps with bullies, cheating exams, and foiling a robbery.',
          'Leonid Gaidai',
          '{"Leonid Gaidai", "Yakov Kostyukovsky", "Moris Slobodskoy"}',
          '{"Aleksandr Demyanenko", "Natalya Seleznyova", "Aleksei Smirnov", "Yuri Nikulin", "Yevgeny Morgunov"}',
          'https://example.com/img/operation_y.jpg'
      ),
      (
          15,
          'The Prestige',
          2006,
          'USA',
          8.523,
          'Two rival magicians in 19th-century London engage in a fierce competition that turns deadly as they obsess over outperforming each other.',
          'Christopher Nolan',
          '{"Jonathan Nolan", "Christopher Nolan", "Christopher Priest"}',
          '{"Hugh Jackman", "Christian Bale", "Michael Caine", "Piper Perabo", "Rebecca Hall"}',
          'https://example.com/img/the_prestige.jpg'
      ),
      (
          16,
          'A Beautiful Mind',
          2001,
          'USA',
          8.555,
          'A brilliant mathematician struggles with schizophrenia as he rises to fame and battles to distinguish reality from illusion.',
          'Ron Howard',
          '{"Akiva Goldsman", "Sylvia Nasar"}',
          '{"Russell Crowe", "Ed Harris", "Jennifer Connelly", "Christopher Plummer", "Paul Bettany"}',
          'https://example.com/img/a_beautiful_mind.jpg'
      ),
      (
          17,
          'Interstellar',
          2014,
          'USA',
          8.591,
          'A team of explorers travels through a wormhole in space in an attempt to ensure humanity’s survival as Earth becomes uninhabitable.',
          'Christopher Nolan',
          '{"Jonathan Nolan", "Christopher Nolan"}',
          '{"Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Mackenzie Foy", "Michael Caine"}',
          'https://example.com/img/interstellar.jpg'
      ),
      (
          18,
          'The Lord of the Rings: The Return of the King',
          2003,
          'New Zealand',
          8.623,
          'The final battle for Middle-earth begins as Frodo and Sam approach Mount Doom to destroy the One Ring once and for all.',
          'Peter Jackson',
          '{"Fran Walsh", "Philippa Boyens", "Peter Jackson"}',
          '{"Elijah Wood", "Viggo Mortensen", "Sean Astin", "Ian McKellen", "Orlando Bloom"}',
          'https://example.com/img/lotr_return_king.jpg'
      ),
      (
          19,
          'Gladiator',
          2000,
          'USA',
          8.577,
          'Betrayed by the empire, a Roman general becomes a gladiator to seek revenge against the corrupt emperor who murdered his family.',
          'Ridley Scott',
          '{"David Franzoni", "John Logan", "William Nicholson"}',
          '{"Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed", "Richard Harris"}',
          'https://example.com/img/gladiator.jpg'
      ),
      (
          20,
          'Back to the Future',
          1985,
          'USA',
          8.626,
          'Teenager Marty McFly is sent back to 1955 in a time machine and must ensure his parents fall in love or risk ceasing to exist.',
          'Robert Zemeckis',
          '{"Robert Zemeckis", "Bob Gale"}',
          '{"Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover", "Thomas F. Wilson"}',
          'https://example.com/img/back_to_the_future.jpg'
      );
